SELECT * FROM POSTGRES.SURVEYS.SURVEY_RESPONSES;

DROP TABLE IF EXISTS surveys.survey_responses_clean;

CREATE TABLE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN AS 
SELECT *
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES;

SELECT * FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

-- 106 rows
SELECT COUNT(*) FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

-- 100 customers
SELECT COUNT(DISTINCT "CUSTOMER_ID") AS CUSTOMER_COUNT
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

SELECT "REWARDS_MEMBER", UPPER(TRIM("REWARDS_MEMBER")) AS "REWARDS_MEMBER_CLEAN"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

SELECT "FREETEXT_RESPONSE", TRIM("FREETEXT_RESPONSE") AS "FREETEXT_RESPONSE_CLEAN"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

BEGIN;

--106 rows
UPDATE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
SET "REWARDS_MEMBER" = UPPER(TRIM("REWARDS_MEMBER")),
"FREETEXT_RESPONSE" = TRIM("FREETEXT_RESPONSE");

SELECT "REWARDS_MEMBER", "FREETEXT_RESPONSE"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

COMMIT;

--ROLLBACK;

BEGIN;

SELECT DISTINCT "SERVICE_FEEDBACK"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

SELECT "SERVICE_FEEDBACK",
CASE WHEN "SERVICE_FEEDBACK" ILIKE ANY (ARRAY['%excellent%', '%great%']) THEN 'EXCELLENT'
WHEN "SERVICE_FEEDBACK" ILIKE '%good%' THEN 'GOOD'
WHEN "SERVICE_FEEDBACK" ILIKE '%average%' THEN 'AVERAGE'
WHEN "SERVICE_FEEDBACK" ILIKE '%poor%' THEN 'POOR'
ELSE NULL END AS "SERVICE_FEEDBACK_CLEAN"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

-- 106 rows updated
UPDATE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
SET "SERVICE_FEEDBACK" = CASE WHEN "SERVICE_FEEDBACK" ILIKE ANY (ARRAY['%excellent%', '%great%']) THEN 'EXCELLENT'
WHEN "SERVICE_FEEDBACK" ILIKE '%good%' THEN 'GOOD'
WHEN "SERVICE_FEEDBACK" ILIKE '%average%' THEN 'AVERAGE'
WHEN "SERVICE_FEEDBACK" ILIKE '%poor%' THEN 'POOR'
ELSE NULL END; 

SELECT *
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

SELECT "SURVEY_DATE", CAST("SURVEY_DATE" AS DATE) AS "SURVEY_DATE_CLEAN"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

UPDATE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
SET "SURVEY_DATE" = CAST("SURVEY_DATE" AS DATE);

ALTER TABLE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
ALTER COLUMN "SURVEY_DATE" TYPE DATE
USING CAST("SURVEY_DATE" AS DATE);


SELECT "ADDRESS"
, SPLIT_PART("ADDRESS", ',', 1) AS ADDRESS_STREET
,SPLIT_PART("ADDRESS", ',', 2) AS ADDRESS_CITY
,SPLIT_PART("ADDRESS", ',', 3) AS ADDRESS_STATE
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

ALTER TABLE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
ADD COLUMN "ADDRESS_STREET" TEXT,
ADD COLUMN "ADDRESS_CITY" TEXT,
ADD COLUMN "ADDRESS_STATE" TEXT;

--106 rows
UPDATE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
SET
"ADDRESS_STREET" = SPLIT_PART("ADDRESS", ',', 1),
"ADDRESS_CITY" = SPLIT_PART("ADDRESS", ',', 2),
"ADDRESS_STATE" = SPLIT_PART("ADDRESS", ',', 3);

SELECT *
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

SELECT "EMAIL", "PHONE", COALESCE("EMAIL", "PHONE", 'Unknown') AS "PREFERRED_CONTACT"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

ALTER TABLE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
ADD COLUMN "PREFERRED_CONTACT" TEXT;

UPDATE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
SET
"PREFERRED_CONTACT" = COALESCE("EMAIL", "PHONE", 'Unknown');

SELECT * FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN ORDER BY "CUSTOMER_ID";

SELECT *
FROM
(SELECT *, COUNT(*) OVER (PARTITION BY "CUSTOMER_ID", "ADDRESS", "SURVEY_DATE", "SURVEY_TIME") AS "DUPLICATE_COUNT"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN)
WHERE "DUPLICATE_COUNT" > 1;

ALTER TABLE POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
ADD COLUMN "SURVEY_ID" BIGSERIAL;

SELECT *, 
ROW_NUMBER() OVER (PARTITION BY "CUSTOMER_ID", "ADDRESS", "SURVEY_DATE", "SURVEY_TIME" ORDER BY "SURVEY_ID") AS "SURVEY_INSTANCE"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

-- 3 rows deleted
WITH DUPLICATES AS (
SELECT *, 
ROW_NUMBER() OVER (PARTITION BY "CUSTOMER_ID", "ADDRESS", "SURVEY_DATE", "SURVEY_TIME" ORDER BY "SURVEY_ID") AS "SURVEY_INSTANCE"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
)
DELETE FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
WHERE "SURVEY_ID" IN (SELECT "SURVEY_ID" FROM DUPLICATES WHERE "SURVEY_INSTANCE" > 1);

SELECT * FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN ORDER BY "CUSTOMER_ID";

-- 3 rows deleted
WITH MULTIPLE_SUBMISSIONS AS (
SELECT *, 
ROW_NUMBER() OVER (PARTITION BY "CUSTOMER_ID", "ADDRESS", "SURVEY_DATE" ORDER BY "SURVEY_TIME" DESC) AS "SURVEY_SURVEY_SUBMISSION"
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
)
DELETE FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN
WHERE "SURVEY_ID" IN (SELECT "SURVEY_ID" FROM MULTIPLE_SUBMISSIONS WHERE "SURVEY_SURVEY_SUBMISSION" > 1);

SELECT * FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN ORDER BY "CUSTOMER_ID";

-- 100 rows
SELECT COUNT(1) FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

-- 100 customers
SELECT COUNT(DISTINCT "CUSTOMER_ID") AS CUSTOMER_COUNT
FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN;

COMMIT;

SELECT * FROM POSTGRES.SURVEYS.SURVEY_RESPONSES_CLEAN ORDER BY "CUSTOMER_ID";

