SELECT * FROM postgres.public.retail_transactions
LIMIT 1000;

SELECT * FROM postgres.public.retail_customer_info
LIMIT 1000;

SELECT
COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS,
SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
AVG(TOTAL_AMOUNT) AS AVG_TRANSACTION_AMT,
MIN(TOTAL_AMOUNT) AS MIN_TRANSACTION_AMT,
MAX(TOTAL_AMOUNT) AS MAX_TRANSACTION_AMT
FROM postgres.public.retail_transactions;


SELECT
CASE WHEN customer.AGE BETWEEN 18 AND 24 THEN '18 - 24'
WHEN AGE BETWEEN 25 AND 34 THEN '25 - 34'
WHEN AGE BETWEEN 35 AND 44 THEN '35 - 44'
WHEN AGE BETWEEN 45 AND 54 THEN '45 - 54'
WHEN AGE BETWEEN 55 AND 64 THEN '55 - 64'
WHEN AGE > 65 THEN '65+'
ELSE 'UNKNOWN' END AS AGE_GROUP,
customer.GENDER AS GENDER,
customer.INCOME AS INCOME_LEVEL,
COUNT(DISTINCT customer.CUSTOMER_ID) AS CUSTOMER_COUNT
FROM postgres.public.retail_customer_info customer
JOIN postgres.public.retail_transactions transactions ON customer.CUSTOMER_ID = transactions.CUSTOMER_ID
GROUP BY AGE_GROUP, GENDER, INCOME_LEVEL;


SELECT
PRODUCT_BRAND,
ROUND(SUM(TOTAL_AMOUNT), 2) AS TOTAL_REVENUE,
ROUND(AVG(RATINGS), 2) AS AVG_RATING,
RANK() OVER (ORDER BY SUM(TOTAL_AMOUNT) DESC) AS REVENUE_RANK
FROM postgres.public.retail_transactions
GROUP BY PRODUCT_BRAND
ORDER BY REVENUE_RANK;

SELECT
DATE_PART('MONTH', TRANSACTION_DATE) AS TRANSACTION_MONTH,
TO_CHAR(TRANSACTION_DATE, 'MONTH') AS TRANSACTION_MONTHNAME,
ROUND(SUM(TOTAL_AMOUNT), 2) AS TOTAL_REVENUE
FROM postgres.public.retail_transactions
WHERE TRANSACTION_DATE IS NOT NULL
GROUP BY TRANSACTION_MONTH, TRANSACTION_MONTHNAME
ORDER BY TRANSACTION_MONTH;

WITH MONTHLY_REVENUE_CUSTOMERS AS (
	SELECT
	DATE_PART('MONTH', TRANSACTION_DATE) AS TRANSACTION_MONTH,
	TO_CHAR(TRANSACTION_DATE, 'MONTH') AS TRANSACTION_MONTHNAME,
	ROUND(SUM(TOTAL_AMOUNT), 2) AS TOTAL_REVENUE,
	COUNT(DISTINCT CUSTOMER_ID) AS CUSTOMER_COUNT
	FROM postgres.public.retail_transactions
	WHERE TRANSACTION_DATE IS NOT NULL
	GROUP BY TRANSACTION_MONTH, TRANSACTION_MONTHNAME
	ORDER BY TRANSACTION_MONTH
)
SELECT
TRANSACTION_MONTH,
TRANSACTION_MONTHNAME,
TOTAL_REVENUE,
CUSTOMER_COUNT,
TOTAL_REVENUE - LAG(TOTAL_REVENUE) OVER (ORDER BY TRANSACTION_MONTH) AS CHANGE_IN_REVENUE,
CUSTOMER_COUNT - LAG(CUSTOMER_COUNT) OVER (ORDER BY TRANSACTION_MONTH) AS CHANGE_IN_CUSTOMER_COUNT
FROM MONTHLY_REVENUE_CUSTOMERS
ORDER BY TRANSACTION_MONTH;

WITH SEGMENT_REVENUE AS (
SELECT
CUSTOMER_SEGMENT,
ROUND(SUM(TOTAL_AMOUNT), 2) AS TOTAL_REVENUE,
ROUND(AVG(RATINGS), 2) AS avg_rating,
COUNT(DISTINCT customers.CUSTOMER_ID) AS CUSTOMER_COUNT
FROM postgres.public.retail_transactions transactions
JOIN postgres.public.retail_customer_info customers ON transactions.CUSTOMER_ID = customers.CUSTOMER_ID
GROUP BY CUSTOMER_SEGMENT
)
SELECT
CUSTOMER_SEGMENT,
TOTAL_REVENUE,
avg_rating,
total_revenue/customer_count AS rev_per_customer,
ROUND(100*total_revenue/SUM(total_revenue) OVER (), 2) AS revenue_share_pct,
RANK() OVER (ORDER BY TOTAL_REVENUE DESC) AS REVENUE_RANK
FROM SEGMENT_REVENUE
ORDER BY REVENUE_RANK;









